/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import java.awt.GridLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author manuelmsni
 */
public class DataViewer extends javax.swing.JFrame {
    
    private Map<String, JTextField> fields;
    
    public DataViewer() {
        this.fields = new HashMap();
        initComponents();
    }

    public JTable getTable() {
        return table;
    }
    
    public Map<String, JTextField> getFields() {
        return fields;
    }

    public JButton getBtnAñadir() {
        return btnAñadir;
    }

    public JButton getBtnBorrar() {
        return btnBorrar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JButton getBtnNuevo() {
        return btnNuevo;
    }

    public JPanel getInputContainer() {
        return inputContainer;
    }

    public void setFieldsEnabled(boolean enabled) {
        for(JTextField tf: fields.values()){
            if(!tf.equals(fields.get("id"))){
                tf.setEnabled(enabled);
            }
        }
    }

    private JTextField createField(String text) {
        JPanel inputs = new JPanel();
        inputs.setLayout(new GridLayout(1, 4));
        inputContainer.add(inputs);
        inputs.add(new JPanel());
        inputs.add(new JLabel(text + ":"));
        JTextField output = new JTextField();
        inputs.add(output);
        inputs.add(new JPanel());
        fields.put(text, output);
        return output;
    }
    
    public void printInputs(Map<String, JTextField> fields){
        System.out.println("\n");
        for(String field: fields.keySet()){
            System.out.println(field);
        }
    }

    public void initEventsInputs() {
        inputContainer.removeAll();
        createField("id").setEnabled(false);
        createField("nombre");
        createField("fecha");
    }

    public void initUserInputs() {
        inputContainer.removeAll();
        createField("id").setEnabled(false);
        createField("nombre");
        createField("apellido");
    }
    
    public void resetFields(){
        fields = new HashMap();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataInputContainer = new javax.swing.JPanel();
        buttonsContainer = new javax.swing.JPanel();
        btnAñadir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        inputContainer = new javax.swing.JPanel();
        dataContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataInputContainer.setPreferredSize(new java.awt.Dimension(155, 200));
        dataInputContainer.setVerifyInputWhenFocusTarget(false);
        dataInputContainer.setLayout(new java.awt.BorderLayout());

        buttonsContainer.setMinimumSize(new java.awt.Dimension(82, 33));
        buttonsContainer.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        btnAñadir.setText("Añadir");
        btnAñadir.setMargin(new java.awt.Insets(5, 14, 5, 14));
        buttonsContainer.add(btnAñadir);

        btnNuevo.setText("Nuevo");
        buttonsContainer.add(btnNuevo);

        btnEditar.setText("Editar");
        buttonsContainer.add(btnEditar);

        btnGuardar.setText("Guardar");
        buttonsContainer.add(btnGuardar);

        btnBorrar.setText("Borrar");
        buttonsContainer.add(btnBorrar);

        dataInputContainer.add(buttonsContainer, java.awt.BorderLayout.WEST);

        inputContainer.setLayout(new java.awt.GridLayout(5, 1));
        dataInputContainer.add(inputContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(dataInputContainer, java.awt.BorderLayout.NORTH);

        dataContainer.setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        dataContainer.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(dataContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel buttonsContainer;
    private javax.swing.JPanel dataContainer;
    private javax.swing.JPanel dataInputContainer;
    private javax.swing.JPanel inputContainer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
